package tutoriasapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import uv.fei.tutorias.bussinesslogic.PersonaDAO;
import uv.fei.tutorias.bussinesslogic.ProgramaEducativoDAO;
import uv.fei.tutorias.bussinesslogic.TutorAcademicoDAO;
import uv.fei.tutorias.domain.Persona;
import uv.fei.tutorias.domain.ProgramaEducativo;
import uv.fei.tutorias.domain.TutorAcademico;

// author @liu
public class GUIRegistroDeEstudiante extends javax.swing.JFrame {

    public GUIRegistroDeEstudiante() {
        initComponents();
        llenarCBEstudiante();
        llenarCBProgramaEducativo();
        llenarCBTutorAcademico();
        this.setTitle("Registro de estudiante");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroDeEstudiante = new javax.swing.JPanel();
        cbEstudiante = new javax.swing.JComboBox<>();
        cbProgramaEducativo = new javax.swing.JComboBox<>();
        cbTutorAcademico = new javax.swing.JComboBox<>();
        tfMatricula = new javax.swing.JTextField();
        lblMatricula = new javax.swing.JLabel();
        lblEstudiante = new javax.swing.JLabel();
        lblProgramaEducativo = new javax.swing.JLabel();
        lblTutorAcademico = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblCamposVacios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMatricula.setText("Matricula");

        lblEstudiante.setText("Estudiante");

        lblProgramaEducativo.setText("Programa Educativo");

        lblTutorAcademico.setText("Tutor Académico");

        btnRegistrar.setLabel("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setLabel("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblCamposVacios.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout pnlRegistroDeEstudianteLayout = new javax.swing.GroupLayout(pnlRegistroDeEstudiante);
        pnlRegistroDeEstudiante.setLayout(pnlRegistroDeEstudianteLayout);
        pnlRegistroDeEstudianteLayout.setHorizontalGroup(
            pnlRegistroDeEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroDeEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroDeEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroDeEstudianteLayout.createSequentialGroup()
                        .addGroup(pnlRegistroDeEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistroDeEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblMatricula)
                                .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEstudiante)
                                .addComponent(cbEstudiante, 0, 300, Short.MAX_VALUE)
                                .addComponent(cbProgramaEducativo, 0, 300, Short.MAX_VALUE)
                                .addComponent(cbTutorAcademico, 0, 300, Short.MAX_VALUE))
                            .addComponent(lblProgramaEducativo)
                            .addComponent(lblTutorAcademico))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroDeEstudianteLayout.createSequentialGroup()
                        .addGap(0, 191, Short.MAX_VALUE)
                        .addGroup(pnlRegistroDeEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroDeEstudianteLayout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRegistrar))
                            .addComponent(lblCamposVacios, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pnlRegistroDeEstudianteLayout.setVerticalGroup(
            pnlRegistroDeEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroDeEstudianteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblProgramaEducativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbProgramaEducativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(lblTutorAcademico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTutorAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(lblCamposVacios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegistroDeEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar)))
        );

        cbEstudiante.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistroDeEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegistroDeEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(camposVacios()) {
            lblCamposVacios.setText("Hay campos vacios*");
        } else {
            this.setVisible(false);
            JOptionPane.showMessageDialog(null, "El estudiante se ha registrado exitosamente.", "Estudiante registrado", 1);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    private boolean camposVacios() {
        boolean camposVacios = true;
        if(!(tfMatricula.getText().trim().isEmpty()) 
                && !(cbEstudiante.getSelectedItem() == null)
                && !(cbProgramaEducativo.getSelectedItem() == null)
                && !(cbTutorAcademico.getSelectedItem() == null)) {
            camposVacios = false;
        }
        return camposVacios;
    }
    
    private void llenarCBEstudiante() {
        PersonaDAO personaDAO = new PersonaDAO();
        ArrayList<Persona> personas = personaDAO.findPersonasByName("");
        
        for(Persona persona : personas) {
            System.out.println(persona);
            cbEstudiante.addItem(persona);
        }
    }
    
    private void llenarCBProgramaEducativo() {
        ProgramaEducativoDAO programaEducativoDAO = new ProgramaEducativoDAO();
        ArrayList<ProgramaEducativo> programasEducativos = programaEducativoDAO.findProgramasEducativosByName("");
        
        for(ProgramaEducativo programaEducativo : programasEducativos) {
            cbProgramaEducativo.addItem(programaEducativo);
        }
    }
    
    private void llenarCBTutorAcademico() {
        TutorAcademicoDAO tutorAcademicoDAO = new TutorAcademicoDAO();
        ArrayList<TutorAcademico> tutoresAcademicos = tutorAcademicoDAO.findTutoresAcademicosByName("");
        
        for(TutorAcademico tutorAcademico : tutoresAcademicos) {
            cbTutorAcademico.addItem(tutorAcademico);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<Persona> cbEstudiante;
    private javax.swing.JComboBox<ProgramaEducativo> cbProgramaEducativo;
    private javax.swing.JComboBox<TutorAcademico> cbTutorAcademico;
    private javax.swing.JLabel lblCamposVacios;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblProgramaEducativo;
    private javax.swing.JLabel lblTutorAcademico;
    private javax.swing.JPanel pnlRegistroDeEstudiante;
    private javax.swing.JTextField tfMatricula;
    // End of variables declaration//GEN-END:variables
}
